definitions:
  workflow: &base_workflow
    environment:
      xcode: 14.2
      vars:
        XCODE_PROJECT: "Wikipedia.xcodeproj"
        XCODE_SCHEME: "Wikipedia"
    triggering:
      events:
        - push
    scripts:
      - name: Upgrade brew
        script: brew install clang-format swiftlint || brew upgrade clang-format swiftlint
      - name: Installing scripts
        script: ./scripts/setup
      - name: Building projects
        script: ./runBuild.sh
      - name: Running tests
        script: 
      - name: Record timings to Benchmarks repo
        script: |
          echo Update Benchmarks repo...
          export BUILD_TIME=$(cat build_time)
          export TESTS_TIME=$(cat tests_time)
          git clone git@github.com:codemagic-ci-cd/codemagic-benchmarks.git
          cd codemagic-benchmarks
          scripts/update_wikipedia.sh
          git config --global user.name "codemagic ci"
          git config --global user.email "devrel@nevercode.io"
          git commit -a -m "update wikipedia app benchmark"
          git push origin main

workflows:
  wikipedia-mac-pro:
    <<: *base_workflow
    name: Wikipedia Workflow with Mac Pro
    instance_type: mac_pro
  wikipedia-mac-mini-m1:
    <<: *base_workflow
    name: Wikipedia Workflow with Mac mini M1
    instance_type: mac_mini_m1
  wikipedia-mac-mini-m2:
    <<: *base_workflow
    name: Wikipedia Workflow with Mac mini M2
